@file:OptIn(ExperimentalJsExport::class)
@file:Suppress("NON_EXPORTABLE_TYPE")

package org.anime_game_servers.multi_proto.gi

import org.anime_game_servers.multi_proto.core.interfaces.ProtoRuntime
import org.anime_game_servers.multi_proto.core.registry.EnumRegistration
import org.anime_game_servers.multi_proto.core.registry.ModelRegistration
import kotlin.js.ExperimentalJsExport
import kotlin.js.JsExport

/**
 * Central hub for the generated proto models. Exposes the KSP-generated metadata (getModels/getEnums)
 * and holds the active [ProtoRuntime] that generated models delegate to. Wire once at startup:
 *
 *   ProtoModelRegistry.use(ProtoRuntimeImpl(ProtoModelRegistry.getModels(), ProtoModelRegistry.getEnums()))
 *
 * `allModels()`/`allEnums()` are generated by the KSP processor into this package.
 */
@JsExport
object ProtoModelRegistry {
    private var runtime: ProtoRuntime? = null

    /** Register the active proto runtime (the descriptor runtime impl). */
    fun use(runtime: ProtoRuntime) {
        this.runtime = runtime
    }

    /** The active runtime; throws if [use] hasn't been called yet. */
    val service: ProtoRuntime
        get() = runtime ?: error("No ProtoRuntime registered. Call ProtoModelRegistry.use(...) once at startup.")

    /** All generated model registrations (for constructing a runtime, and for bulk/dry-run processing). */
    fun getModels(): Collection<ModelRegistration> = allModels()

    /** All generated enum registrations. */
    fun getEnums(): Collection<EnumRegistration> = allEnums()
}
